<?php

namespace BeraniDigitalID\FilamentAccess\Analyzer;

class FilamentRelationManagerAnalyzer extends BaseAnalyzer {
    public static function processAdditionalPermissions(AnalyzerResult $analyzerResult): array
    {
        return parent::processAdditionalPermissions($analyzerResult); // TODO: Change the autogenerated stub
    }
}
